"""
Folder ID: Parcel.Events

Description: Parcel tracking events as CSV files.

Lineage: A deterministic carrier export generated by this example.

File key: "*.csv"

Incremental: false
"""

from weaver import Folder


EVENTS = """Parcel ID,Event sequence,Status,Depot
P-1001,1,Accepted,North
P-1001,2,In transit,Central
P-1002,1,Delivered,South
"""


class Parcel__Events(Folder):
    def read(self):
        with self.staging_folder() as staging:
            (staging.path / "events.csv").write_text(EVENTS, encoding="utf-8")
        return staging
